/**
 * grainDB.js — quick-select catalog scraped from Northern Brewer's live
 * grain collection (northernbrewer.com/collections/grains, Jul 2026).
 * °L is NB's listed color (midpoint of ranges); ppg is the standard
 * published potential for the malt type (NB doesn't list extract).
 * Edit freely — this is just a data file.
 */
export const GRAIN_DB = [
  // ── US base — Rahr / Briess / Canada Malting / MaltEurop ──
  { name: "2-Row Malt - Rahr", ppg: 1.037, lov: 1.9 },
  { name: "Premium Pilsner Malt - Rahr", ppg: 1.037, lov: 1.8 },
  { name: "North Star Pils - Rahr", ppg: 1.037, lov: 1.8 },
  { name: "Rahr To Thee Pils - Rahr", ppg: 1.037, lov: 1.8 },
  { name: "Pale Ale Malt - Rahr", ppg: 1.036, lov: 3.5 },
  { name: "6-Row Malt - Rahr", ppg: 1.035, lov: 1.7 },
  { name: "White Wheat Malt - Rahr", ppg: 1.039, lov: 3 },
  { name: "Red Wheat Malt - Rahr", ppg: 1.038, lov: 3.2 },
  { name: "Unmalted Wheat - Rahr", ppg: 1.036, lov: 2 },
  { name: "2-Row Brewers Malt - Briess", ppg: 1.037, lov: 1.8 },
  { name: "Pale Ale Malt - Briess", ppg: 1.036, lov: 3.5 },
  { name: "Pilsen Malt - Briess", ppg: 1.037, lov: 1.2 },
  { name: "Organic 2-Row Malt - Briess", ppg: 1.037, lov: 1.8 },
  { name: "Wheat Malt - Canada Malting", ppg: 1.039, lov: 1.5 },
  { name: "Superior Pale Ale Malt - Canada Malting", ppg: 1.036, lov: 2.5 },
  { name: "Malta Mexico 2-Row - Malteurop", ppg: 1.037, lov: 2.2 },
  { name: "French Pilsen Malt - Malteurop", ppg: 1.037, lov: 2.0 },
  { name: "Munich 5L Malt - Malteurop", ppg: 1.035, lov: 5 },
  // ── German — Weyermann / Best Malz ──
  { name: "German Pilsner Malt - Weyermann", ppg: 1.037, lov: 1.8 },
  { name: "Bohemian Pilsner Malt - Weyermann", ppg: 1.037, lov: 1.9 },
  { name: "Floor Malted Bohemian Pilsner - Weyermann", ppg: 1.037, lov: 1.8 },
  { name: "Floor Malted Bohemian Dark - Weyermann", ppg: 1.036, lov: 6.5 },
  { name: "Barke Pilsner Malt - Weyermann", ppg: 1.037, lov: 1.9 },
  { name: "Barke Vienna Malt - Weyermann", ppg: 1.036, lov: 3.8 },
  { name: "Barke Munich Malt - Weyermann", ppg: 1.036, lov: 9 },
  { name: "German Pale Ale Malt - Weyermann", ppg: 1.036, lov: 3.0 },
  { name: "German Vienna Malt - Weyermann", ppg: 1.036, lov: 3.8 },
  { name: "German Dark Munich Malt - Weyermann", ppg: 1.036, lov: 9.0 },
  { name: "German Pale Wheat Malt - Weyermann", ppg: 1.039, lov: 1.5 },
  { name: "German Dark Wheat Malt - Weyermann", ppg: 1.039, lov: 7.5 },
  { name: "German Rye Malt - Weyermann", ppg: 1.029, lov: 3.5 },
  { name: "German Acidulated Malt - Weyermann", ppg: 1.027, lov: 1.8 },
  { name: "German Smoked Malt (Rauch) - Weyermann", ppg: 1.037, lov: 2.3 },
  { name: "Oak-Smoked Pale Wheat - Weyermann", ppg: 1.038, lov: 3.1 },
  { name: "German Melanoidin Malt - Weyermann", ppg: 1.037, lov: 27 },
  { name: "Eraclea Italian Pilsner - Weyermann", ppg: 1.037, lov: 1.9 },
  { name: "Isaria 1924 Heirloom Malt - Weyermann", ppg: 1.036, lov: 2.5 },
  { name: "German Pilsen Malt - Best Malz", ppg: 1.037, lov: 1.7 },
  { name: "German Munich Malt - Best Malz", ppg: 1.036, lov: 8.3 },
  { name: "German Red X Malt - Best Malz", ppg: 1.036, lov: 12 },
  { name: "Spelt Malt - Best Malz", ppg: 1.037, lov: 3 },
  // ── UK / Irish — Simpsons / Fawcett / Crisp / Bairds / Warminster ──
  { name: "English Maris Otter - Simpsons", ppg: 1.038, lov: 4.0 },
  { name: "Floor Malted Maris Otter - Warminster", ppg: 1.038, lov: 3.5 },
  { name: "Golden Promise Malt", ppg: 1.038, lov: 3.0 },
  { name: "English Pale Malt - Crisp", ppg: 1.037, lov: 3.0 },
  { name: "English Pearl Malt - Fawcett", ppg: 1.037, lov: 2.6 },
  { name: "Chevallier Heritage Malt - Crisp", ppg: 1.036, lov: 3.5 },
  { name: "Hana Heritage Malt - Crisp", ppg: 1.036, lov: 2.5 },
  { name: "Stout Malt - Malting Co. of Ireland", ppg: 1.037, lov: 1.8 },
  { name: "English Oat Malt - Fawcett", ppg: 1.034, lov: 4 },
  { name: "English Peated Malt - Simpsons", ppg: 1.037, lov: 2.5 },
  { name: "English Torrified Wheat - Crisp", ppg: 1.036, lov: 2 },
  // ── Craft maltsters — Montana Craft / Root Shoot / MaltWerks ──
  { name: "MCM 2-Row - Montana Craft", ppg: 1.037, lov: 2.0 },
  { name: "MCM Pilsner - Montana Craft", ppg: 1.037, lov: 1.9 },
  { name: "MCM Bavarian Pilsner - Montana Craft", ppg: 1.037, lov: 2.0 },
  { name: "MCM British Pale - Montana Craft", ppg: 1.037, lov: 2.6 },
  { name: "MCM Vienna - Montana Craft", ppg: 1.036, lov: 3.3 },
  { name: "MCM Munich Light - Montana Craft", ppg: 1.036, lov: 5.4 },
  { name: "MCM Oat Malt - Montana Craft", ppg: 1.034, lov: 2.8 },
  { name: "MCM Pale White Wheat - Montana Craft", ppg: 1.039, lov: 3.0 },
  { name: "MCM Dextrin Malt - Montana Craft", ppg: 1.033, lov: 2.0 },
  { name: "MCM Cara 20 - Montana Craft", ppg: 1.034, lov: 14.5 },
  { name: "MCM Melanoidin Gold - Montana Craft", ppg: 1.037, lov: 7.5 },
  { name: "Pilsner Malt - Root Shoot", ppg: 1.037, lov: 1.8 },
  { name: "Genie Pale Malt - Root Shoot", ppg: 1.037, lov: 2.5 },
  { name: "English Pale Ale Malt - Root Shoot", ppg: 1.037, lov: 3 },
  { name: "Vienna Malt - Root Shoot", ppg: 1.036, lov: 3.5 },
  { name: "Light Munich 4 - Root Shoot", ppg: 1.036, lov: 4 },
  { name: "Munich 10 Malt - Root Shoot", ppg: 1.035, lov: 10 },
  { name: "Munich Wheat Malt - Root Shoot", ppg: 1.038, lov: 5 },
  { name: "Honey Malt - Root Shoot", ppg: 1.037, lov: 20 },
  { name: "Cara Ruby Malt - Root Shoot", ppg: 1.034, lov: 30 },
  { name: "Rye Malt - Root Shoot", ppg: 1.029, lov: 3.7 },
  { name: "Corn Malt - Root Shoot", ppg: 1.038, lov: 2 },
  { name: "Blue Corn Malt - Root Shoot", ppg: 1.038, lov: 2 },
  { name: "Chit Malt - Root Shoot", ppg: 1.033, lov: 1.5 },
  { name: "Olandsvete Heritage Wheat - Root Shoot", ppg: 1.038, lov: 3 },
  { name: "Pale Malt - MaltWerks", ppg: 1.037, lov: 2.5 },
  { name: "Pilsner Malt - MaltWerks", ppg: 1.037, lov: 1.8 },
  // ── caramel / crystal ──
  { name: "Carapils Malt - Briess", ppg: 1.033, lov: 1.5 },
  { name: "Caramel 10L - Briess", ppg: 1.035, lov: 10 },
  { name: "Caramel 20L - Briess", ppg: 1.035, lov: 20 },
  { name: "Caramel 40L - Briess", ppg: 1.034, lov: 40 },
  { name: "Caramel 60L - Briess", ppg: 1.034, lov: 60 },
  { name: "Caramel 80L - Briess", ppg: 1.034, lov: 80 },
  { name: "Caramel 90L - Briess", ppg: 1.034, lov: 90 },
  { name: "Caramel 120L - Briess", ppg: 1.033, lov: 120 },
  { name: "Caramel Vienne 20L - Briess", ppg: 1.035, lov: 20 },
  { name: "Crystal Red Malt - Briess", ppg: 1.034, lov: 100 },
  { name: "Honey Malt (20-30L)", ppg: 1.037, lov: 25 },
  { name: "American Honey Malt - Briess", ppg: 1.037, lov: 25 },
  { name: "German Carafoam - Weyermann", ppg: 1.033, lov: 1.8 },
  { name: "German Carahell - Weyermann", ppg: 1.034, lov: 11 },
  { name: "German CaraRed - Weyermann", ppg: 1.034, lov: 20 },
  { name: "German Caramunich I - Weyermann", ppg: 1.034, lov: 34 },
  { name: "German Caramunich II - Weyermann", ppg: 1.034, lov: 46 },
  { name: "German Caramunich III - Weyermann", ppg: 1.034, lov: 57 },
  { name: "German CaraWheat - Weyermann", ppg: 1.035, lov: 45 },
  { name: "English Crystal Light - Simpsons", ppg: 1.034, lov: 33 },
  { name: "English Medium Crystal - Fawcett", ppg: 1.034, lov: 45 },
  { name: "English Dark Crystal - Fawcett", ppg: 1.034, lov: 75 },
  { name: "English Extra Dark Crystal - Simpsons", ppg: 1.033, lov: 160 },
  { name: "English Crystal 77L - Crisp", ppg: 1.034, lov: 77 },
  { name: "English Crystal Rye - Fawcett", ppg: 1.032, lov: 75 },
  { name: "English Carastan - Bairds", ppg: 1.034, lov: 35 },
  { name: "English DRC - Simpsons", ppg: 1.033, lov: 45 },
  { name: "English Golden Naked Oats - Simpsons", ppg: 1.033, lov: 10 },
  { name: "Belgian Cara 8 Pils - Dingemans", ppg: 1.034, lov: 6 },
  { name: "Belgian Cara 20 (Caravienne) - Dingemans", ppg: 1.034, lov: 21 },
  { name: "Belgian Cara 45 - Dingemans", ppg: 1.034, lov: 45 },
  { name: "Special B - Dingemans", ppg: 1.030, lov: 130 },
  // ── toasted / biscuit / brown ──
  { name: "Victory Malt - Briess", ppg: 1.034, lov: 28 },
  { name: "Special Roast - Briess", ppg: 1.033, lov: 50 },
  { name: "Aromatic Malt - Briess", ppg: 1.036, lov: 20 },
  { name: "Bonlander Munich - Briess", ppg: 1.036, lov: 10 },
  { name: "Ashburne Mild Malt - Briess", ppg: 1.036, lov: 5.3 },
  { name: "Briess Lighthouse Munich", ppg: 1.036, lov: 6 },
  { name: "Heritage Gold Malt - Briess", ppg: 1.036, lov: 6 },
  { name: "Vienna Goldpils - Briess", ppg: 1.036, lov: 3.5 },
  { name: "Cherrywood Smoked - Briess", ppg: 1.037, lov: 4 },
  { name: "Rye Malt - Briess", ppg: 1.029, lov: 3.7 },
  { name: "Blonde RoastOat - Briess", ppg: 1.033, lov: 4 },
  { name: "Biscuit Malt", ppg: 1.036, lov: 24.5 },
  { name: "Belgian Aromatic - Dingemans", ppg: 1.036, lov: 19 },
  { name: "Belgian Munich - Dingemans", ppg: 1.036, lov: 5.5 },
  { name: "Belgian Pilsner - Dingemans", ppg: 1.037, lov: 1.6 },
  { name: "Belgian Pale Ale - Dingemans", ppg: 1.037, lov: 3.9 },
  { name: "English Amber Malt - Simpsons", ppg: 1.032, lov: 27 },
  { name: "English Brown Malt - Fawcett", ppg: 1.032, lov: 65 },
  { name: "IPA Malt - Gambrinus", ppg: 1.036, lov: 3 },
  // ── roasted / dark ──
  { name: "Chocolate Malt - Briess", ppg: 1.028, lov: 350 },
  { name: "Organic Chocolate - Briess", ppg: 1.028, lov: 350 },
  { name: "Black (Patent) Malt - Briess", ppg: 1.025, lov: 500 },
  { name: "Midnight Wheat - Briess", ppg: 1.025, lov: 550 },
  { name: "Light Roasted Barley - Briess", ppg: 1.025, lov: 300 },
  { name: "English Coffee Malt - Simpsons", ppg: 1.033, lov: 150 },
  { name: "English Pale Chocolate - Fawcett", ppg: 1.034, lov: 215 },
  { name: "English Chocolate Malt - Simpsons", ppg: 1.028, lov: 445 },
  { name: "English Black Malt - Simpsons", ppg: 1.025, lov: 550 },
  { name: "English Roasted Barley", ppg: 1.025, lov: 675 },
  { name: "German Chocolate Rye - Weyermann", ppg: 1.029, lov: 244 },
  { name: "German Carafa I - Weyermann", ppg: 1.032, lov: 337 },
  { name: "German Carafa II - Weyermann", ppg: 1.032, lov: 430 },
  { name: "German Carafa III - Weyermann", ppg: 1.032, lov: 525 },
  { name: "Dehusked Carafa I - Weyermann", ppg: 1.032, lov: 337 },
  { name: "Dehusked Carafa II - Weyermann", ppg: 1.032, lov: 430 },
  { name: "Dehusked Carafa III - Weyermann", ppg: 1.032, lov: 525 },
  { name: "Belgian Debittered Black - Dingemans", ppg: 1.030, lov: 550 },
  // ── flaked / adjuncts ──
  { name: "Flaked Oats", ppg: 1.033, lov: 2.2 },
  { name: "Flaked Wheat", ppg: 1.034, lov: 2 },
  { name: "Flaked Barley", ppg: 1.032, lov: 2 },
  { name: "Flaked Maize (Corn)", ppg: 1.039, lov: 0.5 },
  { name: "Flaked Rice", ppg: 1.038, lov: 0.5 },
  { name: "Flaked Rye", ppg: 1.036, lov: 2.8 },
  { name: "Flaked Torrefied Rice - Crisp", ppg: 1.038, lov: 0.5 },
  { name: "Rice Hulls (no extract)", ppg: 1.000, lov: 0 },
  // ── sugars & extracts ──
  { name: "Lactose", ppg: 1.043, lov: 0 },
  { name: "Corn Sugar (Dextrose)", ppg: 1.037, lov: 0 },
  { name: "Table Sugar", ppg: 1.046, lov: 0 },
  { name: "Honey", ppg: 1.032, lov: 1 },
  { name: "Golden Light DME - Briess", ppg: 1.044, lov: 4 },
  { name: "Pilsen Light LME - Briess", ppg: 1.036, lov: 2 },
];

/**
 * Brewing salts — ion contribution in ppm per gram per gallon of water.
 * Same numbers the EZ Water calculator uses.
 */
export const SALT_DB = {
  "Gypsum":            { Ca: 61.5, SO4: 147.4 },
  "Calcium Chloride":  { Ca: 72.0, Cl: 127.4 },
  "Epsom Salt":        { Mg: 26.1, SO4: 103.0 },
  "Canning Salt (NaCl)": { Na: 103.9, Cl: 160.3 },
  "Baking Soda":       { Na: 72.3, HCO3: 191.0 },
  "Chalk":             { Ca: 105.6, HCO3: 322.3 },
  "Slaked Lime":       { Ca: 143.4, HCO3: 0 },
};
export const SALT_NAMES = Object.keys(SALT_DB);
export const IONS = ["Ca", "Mg", "Na", "Cl", "SO4"];
