/**
 * hopDB.js — quick-select hop catalog scraped from Northern Brewer's live
 * hops collection (northernbrewer.com/collections/hops, Jul 2026).
 * aa = midpoint of NB's listed alpha range — always override with the AA%
 * printed on your actual bag for accurate IBUs. Cryo/LupuLN2/Amplifire
 * products listed separately (roughly 2× alpha, use ~half the ounces).
 */
export const HOP_DB = [
  // ── American aroma / dual ──
  { name: "Cascade", aa: 6.7, notes: "grapefruit, floral" },
  { name: "Centennial", aa: 10.5, notes: "citrus, pine" },
  { name: "Citra", aa: 12.0, notes: "grapefruit, tropical" },
  { name: "Mosaic", aa: 12.3, notes: "berry, mango, pine" },
  { name: "Simcoe", aa: 13.0, notes: "pine, passionfruit" },
  { name: "Amarillo", aa: 9.5, notes: "orange citrus" },
  { name: "Chinook", aa: 13.0, notes: "pine, grapefruit, spice" },
  { name: "Columbus (CTZ)", aa: 16.0, notes: "dank, pungent" },
  { name: "Sabro", aa: 14.0, notes: "coconut, tangerine, cream" },
  { name: "Strata", aa: 11.8, notes: "strawberry, passionfruit, dank" },
  { name: "Idaho 7", aa: 12.2, notes: "apricot, tropical, resin" },
  { name: "El Dorado", aa: 15.0, notes: "candy, stone fruit" },
  { name: "Cashmere", aa: 8.4, notes: "melon, lemon-lime" },
  { name: "Loral", aa: 12.4, notes: "floral, dark fruit, pepper" },
  { name: "Lemondrop", aa: 6.0, notes: "lemon, mint" },
  { name: "Ahtanum", aa: 5.3, notes: "citrus, earthy" },
  { name: "Palisade", aa: 7.5, notes: "apricot, grass" },
  { name: "Glacier", aa: 6.5, notes: "sweet fruit, herbal" },
  { name: "Sorachi Ace", aa: 13.0, notes: "lemon, dill" },
  { name: "Crystal", aa: 4.8, notes: "woody, floral" },
  { name: "Mt. Hood", aa: 5.5, notes: "hallertau-like" },
  { name: "Liberty", aa: 4.0, notes: "noble-like, subtle" },
  { name: "Sterling", aa: 9.0, notes: "saaz-like, citrus" },
  { name: "Vanguard", aa: 5.5, notes: "noble-like" },
  { name: "Willamette", aa: 5.5, notes: "earthy, blackcurrant" },
  { name: "Goldings (US)", aa: 5.0, notes: "earthy, honey" },
  { name: "Fuggle (US)", aa: 4.8, notes: "earthy, woody" },
  { name: "Saaz (US)", aa: 5.0, notes: "spicy, earthy" },
  { name: "Tettnang (US)", aa: 4.8, notes: "spicy, floral" },
  { name: "Perle (US)", aa: 8.3, notes: "minty, spicy" },
  { name: "Northern Brewer (US)", aa: 8.0, notes: "woody, minty" },
  { name: "Cluster", aa: 7.0, notes: "classic American, fruity" },
  { name: "Brewer's Gold (US)", aa: 9.5, notes: "blackcurrant, spicy" },
  { name: "Comet", aa: 10.9, notes: "wild grapefruit" },
  { name: "Zappa", aa: 7.0, notes: "neomexicanus — fruity, funky" },
  { name: "Vista", aa: 10.5, notes: "stone fruit, melon" },
  { name: "Trident", aa: 12.5, notes: "tropical blend" },
  { name: "Calypso", aa: 13.0, notes: "apple, pear" },
  { name: "Sultana (Denali)", aa: 14.5, notes: "pineapple, pine" },
  { name: "Horizon", aa: 10.4, notes: "clean, floral" },
  { name: "Zamba", aa: 10.0, notes: "tropical blend" },
  { name: "Tahoma", aa: 7.6, notes: "citrus, cedar" },
  { name: "Triumph", aa: 10.5, notes: "citrus, peach" },
  { name: "Dolcita", aa: 11.5, notes: "sweet citrus" },
  { name: "Contessa", aa: 4.0, notes: "light citrus, pear" },
  { name: "Helios", aa: 19.5, notes: "high-alpha, citrus" },
  { name: "Erebus", aa: 9.5, notes: "dark fruit" },
  // ── American bittering ──
  { name: "Magnum (US)", aa: 13.8, notes: "clean bittering" },
  { name: "Warrior", aa: 15.5, notes: "clean bittering" },
  { name: "Nugget", aa: 13.5, notes: "herbal bittering" },
  { name: "Apollo", aa: 17.0, notes: "high-alpha, resin" },
  { name: "Bravo", aa: 15.5, notes: "fruity bittering" },
  { name: "Summit", aa: 17.5, notes: "tangerine, dank" },
  { name: "Galena", aa: 13.3, notes: "classic bittering" },
  // ── Southern hemisphere ──
  { name: "Galaxy", aa: 13.8, notes: "passionfruit, peach" },
  { name: "Nelson Sauvin", aa: 12.5, notes: "white wine, gooseberry" },
  { name: "Motueka", aa: 7.0, notes: "lime, lemongrass" },
  { name: "Superdelic", aa: 10.5, notes: "candy, berry, citrus" },
  { name: "Nectaron", aa: 12.0, notes: "pineapple, stone fruit" },
  { name: "Wakatu", aa: 7.5, notes: "lime, vanilla" },
  { name: "Vic Secret", aa: 18.5, notes: "pineapple, pine" },
  { name: "Pink", aa: 12.7, notes: "berries, cream" },
  // ── German / Czech / French noble ──
  { name: "Saaz (Czech)", aa: 3.5, notes: "noble — spicy, earthy" },
  { name: "Hallertau (German)", aa: 4.3, notes: "noble — floral, herbal" },
  { name: "Tettnang (German)", aa: 4.5, notes: "noble — spicy, floral" },
  { name: "Hersbrucker", aa: 2.8, notes: "floral, fruity" },
  { name: "Tradition", aa: 5.5, notes: "hallertau family, herbal" },
  { name: "Perle (German)", aa: 6.5, notes: "minty, spicy" },
  { name: "Northern Brewer (German)", aa: 8.0, notes: "woody, minty" },
  { name: "Magnum (German)", aa: 13.5, notes: "clean bittering" },
  { name: "Mandarina Bavaria", aa: 8.5, notes: "tangerine" },
  { name: "Hallertau Blanc", aa: 10.5, notes: "white wine, gooseberry" },
  { name: "Strisselspalt", aa: 2.2, notes: "French — floral, herbal" },
  // ── English ──
  { name: "East Kent Goldings", aa: 5.3, notes: "earthy, honey" },
  { name: "Fuggle (UK)", aa: 5.0, notes: "earthy, woody" },
  { name: "Challenger", aa: 8.0, notes: "cedar, green tea" },
  { name: "Target", aa: 11.0, notes: "sage, spice, bittering" },
  { name: "First Gold", aa: 8.0, notes: "orange, marmalade" },
  { name: "Northdown", aa: 8.5, notes: "berry, cedar" },
  { name: "Styrian Goldings", aa: 5.3, notes: "earthy, white pepper" },
  // ── Cryo / concentrated (≈2× alpha — use about half the ounces) ──
  { name: "Citra Cryo", aa: 25.0, notes: "cryo — grapefruit, tropical" },
  { name: "Mosaic Cryo", aa: 22.0, notes: "cryo — berry, mango" },
  { name: "Simcoe Cryo", aa: 23.0, notes: "cryo — pine, passionfruit" },
  { name: "Cascade Cryo", aa: 12.0, notes: "cryo — grapefruit" },
  { name: "Centennial Cryo", aa: 14.3, notes: "cryo — citrus, pine" },
  { name: "Amarillo Cryo", aa: 16.0, notes: "cryo — orange" },
  { name: "Strata Cryo", aa: 21.3, notes: "cryo — strawberry, dank" },
  { name: "Nelson Sauvin Amplifire", aa: 15.0, notes: "concentrated — white wine" },
  { name: "Motueka Amplifire", aa: 9.5, notes: "concentrated — lime" },
  { name: "Rakau Amplifire", aa: 15.5, notes: "concentrated — apricot" },
  { name: "Riwaka Amplifire", aa: 10.0, notes: "concentrated — grapefruit" },
];
